/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDeDatosRouteImport } from './routes/politica-de-datos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquilibrioRouteImport } from './routes/equilibrio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquilibrioIndexRouteImport } from './routes/equilibrio/index'
import { Route as EquilibrioRegistroExitosoRouteImport } from './routes/equilibrio/registro-exitoso'

const PoliticaDeDatosRoute = PoliticaDeDatosRouteImport.update({
  id: '/politica-de-datos',
  path: '/politica-de-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquilibrioRoute = EquilibrioRouteImport.update({
  id: '/equilibrio',
  path: '/equilibrio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquilibrioIndexRoute = EquilibrioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquilibrioRoute,
} as any)
const EquilibrioRegistroExitosoRoute =
  EquilibrioRegistroExitosoRouteImport.update({
    id: '/registro-exitoso',
    path: '/registro-exitoso',
    getParentRoute: () => EquilibrioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/equilibrio': typeof EquilibrioRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/equilibrio/registro-exitoso': typeof EquilibrioRegistroExitosoRoute
  '/equilibrio/': typeof EquilibrioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/equilibrio/registro-exitoso': typeof EquilibrioRegistroExitosoRoute
  '/equilibrio': typeof EquilibrioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/equilibrio': typeof EquilibrioRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/equilibrio/registro-exitoso': typeof EquilibrioRegistroExitosoRoute
  '/equilibrio/': typeof EquilibrioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/equilibrio'
    | '/login'
    | '/politica-de-datos'
    | '/equilibrio/registro-exitoso'
    | '/equilibrio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/politica-de-datos'
    | '/equilibrio/registro-exitoso'
    | '/equilibrio'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/equilibrio'
    | '/login'
    | '/politica-de-datos'
    | '/equilibrio/registro-exitoso'
    | '/equilibrio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EquilibrioRoute: typeof EquilibrioRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliticaDeDatosRoute: typeof PoliticaDeDatosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-datos': {
      id: '/politica-de-datos'
      path: '/politica-de-datos'
      fullPath: '/politica-de-datos'
      preLoaderRoute: typeof PoliticaDeDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equilibrio': {
      id: '/equilibrio'
      path: '/equilibrio'
      fullPath: '/equilibrio'
      preLoaderRoute: typeof EquilibrioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equilibrio/': {
      id: '/equilibrio/'
      path: '/'
      fullPath: '/equilibrio/'
      preLoaderRoute: typeof EquilibrioIndexRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/equilibrio/registro-exitoso': {
      id: '/equilibrio/registro-exitoso'
      path: '/registro-exitoso'
      fullPath: '/equilibrio/registro-exitoso'
      preLoaderRoute: typeof EquilibrioRegistroExitosoRouteImport
      parentRoute: typeof EquilibrioRoute
    }
  }
}

interface EquilibrioRouteChildren {
  EquilibrioRegistroExitosoRoute: typeof EquilibrioRegistroExitosoRoute
  EquilibrioIndexRoute: typeof EquilibrioIndexRoute
}

const EquilibrioRouteChildren: EquilibrioRouteChildren = {
  EquilibrioRegistroExitosoRoute: EquilibrioRegistroExitosoRoute,
  EquilibrioIndexRoute: EquilibrioIndexRoute,
}

const EquilibrioRouteWithChildren = EquilibrioRoute._addFileChildren(
  EquilibrioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EquilibrioRoute: EquilibrioRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliticaDeDatosRoute: PoliticaDeDatosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
