/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDeDatosRouteImport } from './routes/politica-de-datos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EquilibrioRouteImport } from './routes/equilibrio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventosIndexRouteImport } from './routes/eventos/index'
import { Route as EquilibrioIndexRouteImport } from './routes/equilibrio/index'
import { Route as EventosSeriesSlugRouteImport } from './routes/eventos/$seriesSlug'
import { Route as EquilibrioRegistroExitosoRouteImport } from './routes/equilibrio/registro-exitoso'
import { Route as EquilibrioFeedbackExitosoRouteImport } from './routes/equilibrio/feedback-exitoso'
import { Route as EquilibrioFeedbackRouteImport } from './routes/equilibrio/feedback'
import { Route as EquilibrioConfirmarAsistenciaRouteImport } from './routes/equilibrio/confirmar-asistencia'
import { Route as EquilibrioConexionExitosaRouteImport } from './routes/equilibrio/conexion-exitosa'
import { Route as EquilibrioConexionRouteImport } from './routes/equilibrio/conexion'
import { Route as EquilibrioAsistenciaConfirmadaRouteImport } from './routes/equilibrio/asistencia-confirmada'
import { Route as EventosSeriesSlugIndexRouteImport } from './routes/eventos/$seriesSlug/index'
import { Route as EventosSeriesSlugRegistroExitosoRouteImport } from './routes/eventos/$seriesSlug/registro-exitoso'
import { Route as EventosSeriesSlugFeedbackExitosoRouteImport } from './routes/eventos/$seriesSlug/feedback-exitoso'
import { Route as EventosSeriesSlugFeedbackRouteImport } from './routes/eventos/$seriesSlug/feedback'
import { Route as EventosSeriesSlugConfirmarAsistenciaRouteImport } from './routes/eventos/$seriesSlug/confirmar-asistencia'
import { Route as EventosSeriesSlugConexionExitosaRouteImport } from './routes/eventos/$seriesSlug/conexion-exitosa'
import { Route as EventosSeriesSlugConexionRouteImport } from './routes/eventos/$seriesSlug/conexion'
import { Route as EventosSeriesSlugAsistenciaConfirmadaRouteImport } from './routes/eventos/$seriesSlug/asistencia-confirmada'

const PoliticaDeDatosRoute = PoliticaDeDatosRouteImport.update({
  id: '/politica-de-datos',
  path: '/politica-de-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquilibrioRoute = EquilibrioRouteImport.update({
  id: '/equilibrio',
  path: '/equilibrio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const EquilibrioIndexRoute = EquilibrioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquilibrioRoute,
} as any)
const EventosSeriesSlugRoute = EventosSeriesSlugRouteImport.update({
  id: '/$seriesSlug',
  path: '/$seriesSlug',
  getParentRoute: () => EventosRoute,
} as any)
const EquilibrioRegistroExitosoRoute =
  EquilibrioRegistroExitosoRouteImport.update({
    id: '/registro-exitoso',
    path: '/registro-exitoso',
    getParentRoute: () => EquilibrioRoute,
  } as any)
const EquilibrioFeedbackExitosoRoute =
  EquilibrioFeedbackExitosoRouteImport.update({
    id: '/feedback-exitoso',
    path: '/feedback-exitoso',
    getParentRoute: () => EquilibrioRoute,
  } as any)
const EquilibrioFeedbackRoute = EquilibrioFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => EquilibrioRoute,
} as any)
const EquilibrioConfirmarAsistenciaRoute =
  EquilibrioConfirmarAsistenciaRouteImport.update({
    id: '/confirmar-asistencia',
    path: '/confirmar-asistencia',
    getParentRoute: () => EquilibrioRoute,
  } as any)
const EquilibrioConexionExitosaRoute =
  EquilibrioConexionExitosaRouteImport.update({
    id: '/conexion-exitosa',
    path: '/conexion-exitosa',
    getParentRoute: () => EquilibrioRoute,
  } as any)
const EquilibrioConexionRoute = EquilibrioConexionRouteImport.update({
  id: '/conexion',
  path: '/conexion',
  getParentRoute: () => EquilibrioRoute,
} as any)
const EquilibrioAsistenciaConfirmadaRoute =
  EquilibrioAsistenciaConfirmadaRouteImport.update({
    id: '/asistencia-confirmada',
    path: '/asistencia-confirmada',
    getParentRoute: () => EquilibrioRoute,
  } as any)
const EventosSeriesSlugIndexRoute = EventosSeriesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosSeriesSlugRoute,
} as any)
const EventosSeriesSlugRegistroExitosoRoute =
  EventosSeriesSlugRegistroExitosoRouteImport.update({
    id: '/registro-exitoso',
    path: '/registro-exitoso',
    getParentRoute: () => EventosSeriesSlugRoute,
  } as any)
const EventosSeriesSlugFeedbackExitosoRoute =
  EventosSeriesSlugFeedbackExitosoRouteImport.update({
    id: '/feedback-exitoso',
    path: '/feedback-exitoso',
    getParentRoute: () => EventosSeriesSlugRoute,
  } as any)
const EventosSeriesSlugFeedbackRoute =
  EventosSeriesSlugFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => EventosSeriesSlugRoute,
  } as any)
const EventosSeriesSlugConfirmarAsistenciaRoute =
  EventosSeriesSlugConfirmarAsistenciaRouteImport.update({
    id: '/confirmar-asistencia',
    path: '/confirmar-asistencia',
    getParentRoute: () => EventosSeriesSlugRoute,
  } as any)
const EventosSeriesSlugConexionExitosaRoute =
  EventosSeriesSlugConexionExitosaRouteImport.update({
    id: '/conexion-exitosa',
    path: '/conexion-exitosa',
    getParentRoute: () => EventosSeriesSlugRoute,
  } as any)
const EventosSeriesSlugConexionRoute =
  EventosSeriesSlugConexionRouteImport.update({
    id: '/conexion',
    path: '/conexion',
    getParentRoute: () => EventosSeriesSlugRoute,
  } as any)
const EventosSeriesSlugAsistenciaConfirmadaRoute =
  EventosSeriesSlugAsistenciaConfirmadaRouteImport.update({
    id: '/asistencia-confirmada',
    path: '/asistencia-confirmada',
    getParentRoute: () => EventosSeriesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/equilibrio': typeof EquilibrioRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/equilibrio/asistencia-confirmada': typeof EquilibrioAsistenciaConfirmadaRoute
  '/equilibrio/conexion': typeof EquilibrioConexionRoute
  '/equilibrio/conexion-exitosa': typeof EquilibrioConexionExitosaRoute
  '/equilibrio/confirmar-asistencia': typeof EquilibrioConfirmarAsistenciaRoute
  '/equilibrio/feedback': typeof EquilibrioFeedbackRoute
  '/equilibrio/feedback-exitoso': typeof EquilibrioFeedbackExitosoRoute
  '/equilibrio/registro-exitoso': typeof EquilibrioRegistroExitosoRoute
  '/eventos/$seriesSlug': typeof EventosSeriesSlugRouteWithChildren
  '/equilibrio/': typeof EquilibrioIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$seriesSlug/asistencia-confirmada': typeof EventosSeriesSlugAsistenciaConfirmadaRoute
  '/eventos/$seriesSlug/conexion': typeof EventosSeriesSlugConexionRoute
  '/eventos/$seriesSlug/conexion-exitosa': typeof EventosSeriesSlugConexionExitosaRoute
  '/eventos/$seriesSlug/confirmar-asistencia': typeof EventosSeriesSlugConfirmarAsistenciaRoute
  '/eventos/$seriesSlug/feedback': typeof EventosSeriesSlugFeedbackRoute
  '/eventos/$seriesSlug/feedback-exitoso': typeof EventosSeriesSlugFeedbackExitosoRoute
  '/eventos/$seriesSlug/registro-exitoso': typeof EventosSeriesSlugRegistroExitosoRoute
  '/eventos/$seriesSlug/': typeof EventosSeriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/equilibrio/asistencia-confirmada': typeof EquilibrioAsistenciaConfirmadaRoute
  '/equilibrio/conexion': typeof EquilibrioConexionRoute
  '/equilibrio/conexion-exitosa': typeof EquilibrioConexionExitosaRoute
  '/equilibrio/confirmar-asistencia': typeof EquilibrioConfirmarAsistenciaRoute
  '/equilibrio/feedback': typeof EquilibrioFeedbackRoute
  '/equilibrio/feedback-exitoso': typeof EquilibrioFeedbackExitosoRoute
  '/equilibrio/registro-exitoso': typeof EquilibrioRegistroExitosoRoute
  '/equilibrio': typeof EquilibrioIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/eventos/$seriesSlug/asistencia-confirmada': typeof EventosSeriesSlugAsistenciaConfirmadaRoute
  '/eventos/$seriesSlug/conexion': typeof EventosSeriesSlugConexionRoute
  '/eventos/$seriesSlug/conexion-exitosa': typeof EventosSeriesSlugConexionExitosaRoute
  '/eventos/$seriesSlug/confirmar-asistencia': typeof EventosSeriesSlugConfirmarAsistenciaRoute
  '/eventos/$seriesSlug/feedback': typeof EventosSeriesSlugFeedbackRoute
  '/eventos/$seriesSlug/feedback-exitoso': typeof EventosSeriesSlugFeedbackExitosoRoute
  '/eventos/$seriesSlug/registro-exitoso': typeof EventosSeriesSlugRegistroExitosoRoute
  '/eventos/$seriesSlug': typeof EventosSeriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/equilibrio': typeof EquilibrioRouteWithChildren
  '/eventos': typeof EventosRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-datos': typeof PoliticaDeDatosRoute
  '/equilibrio/asistencia-confirmada': typeof EquilibrioAsistenciaConfirmadaRoute
  '/equilibrio/conexion': typeof EquilibrioConexionRoute
  '/equilibrio/conexion-exitosa': typeof EquilibrioConexionExitosaRoute
  '/equilibrio/confirmar-asistencia': typeof EquilibrioConfirmarAsistenciaRoute
  '/equilibrio/feedback': typeof EquilibrioFeedbackRoute
  '/equilibrio/feedback-exitoso': typeof EquilibrioFeedbackExitosoRoute
  '/equilibrio/registro-exitoso': typeof EquilibrioRegistroExitosoRoute
  '/eventos/$seriesSlug': typeof EventosSeriesSlugRouteWithChildren
  '/equilibrio/': typeof EquilibrioIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$seriesSlug/asistencia-confirmada': typeof EventosSeriesSlugAsistenciaConfirmadaRoute
  '/eventos/$seriesSlug/conexion': typeof EventosSeriesSlugConexionRoute
  '/eventos/$seriesSlug/conexion-exitosa': typeof EventosSeriesSlugConexionExitosaRoute
  '/eventos/$seriesSlug/confirmar-asistencia': typeof EventosSeriesSlugConfirmarAsistenciaRoute
  '/eventos/$seriesSlug/feedback': typeof EventosSeriesSlugFeedbackRoute
  '/eventos/$seriesSlug/feedback-exitoso': typeof EventosSeriesSlugFeedbackExitosoRoute
  '/eventos/$seriesSlug/registro-exitoso': typeof EventosSeriesSlugRegistroExitosoRoute
  '/eventos/$seriesSlug/': typeof EventosSeriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/equilibrio'
    | '/eventos'
    | '/login'
    | '/politica-de-datos'
    | '/equilibrio/asistencia-confirmada'
    | '/equilibrio/conexion'
    | '/equilibrio/conexion-exitosa'
    | '/equilibrio/confirmar-asistencia'
    | '/equilibrio/feedback'
    | '/equilibrio/feedback-exitoso'
    | '/equilibrio/registro-exitoso'
    | '/eventos/$seriesSlug'
    | '/equilibrio/'
    | '/eventos/'
    | '/eventos/$seriesSlug/asistencia-confirmada'
    | '/eventos/$seriesSlug/conexion'
    | '/eventos/$seriesSlug/conexion-exitosa'
    | '/eventos/$seriesSlug/confirmar-asistencia'
    | '/eventos/$seriesSlug/feedback'
    | '/eventos/$seriesSlug/feedback-exitoso'
    | '/eventos/$seriesSlug/registro-exitoso'
    | '/eventos/$seriesSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/politica-de-datos'
    | '/equilibrio/asistencia-confirmada'
    | '/equilibrio/conexion'
    | '/equilibrio/conexion-exitosa'
    | '/equilibrio/confirmar-asistencia'
    | '/equilibrio/feedback'
    | '/equilibrio/feedback-exitoso'
    | '/equilibrio/registro-exitoso'
    | '/equilibrio'
    | '/eventos'
    | '/eventos/$seriesSlug/asistencia-confirmada'
    | '/eventos/$seriesSlug/conexion'
    | '/eventos/$seriesSlug/conexion-exitosa'
    | '/eventos/$seriesSlug/confirmar-asistencia'
    | '/eventos/$seriesSlug/feedback'
    | '/eventos/$seriesSlug/feedback-exitoso'
    | '/eventos/$seriesSlug/registro-exitoso'
    | '/eventos/$seriesSlug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/equilibrio'
    | '/eventos'
    | '/login'
    | '/politica-de-datos'
    | '/equilibrio/asistencia-confirmada'
    | '/equilibrio/conexion'
    | '/equilibrio/conexion-exitosa'
    | '/equilibrio/confirmar-asistencia'
    | '/equilibrio/feedback'
    | '/equilibrio/feedback-exitoso'
    | '/equilibrio/registro-exitoso'
    | '/eventos/$seriesSlug'
    | '/equilibrio/'
    | '/eventos/'
    | '/eventos/$seriesSlug/asistencia-confirmada'
    | '/eventos/$seriesSlug/conexion'
    | '/eventos/$seriesSlug/conexion-exitosa'
    | '/eventos/$seriesSlug/confirmar-asistencia'
    | '/eventos/$seriesSlug/feedback'
    | '/eventos/$seriesSlug/feedback-exitoso'
    | '/eventos/$seriesSlug/registro-exitoso'
    | '/eventos/$seriesSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EquilibrioRoute: typeof EquilibrioRouteWithChildren
  EventosRoute: typeof EventosRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliticaDeDatosRoute: typeof PoliticaDeDatosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-datos': {
      id: '/politica-de-datos'
      path: '/politica-de-datos'
      fullPath: '/politica-de-datos'
      preLoaderRoute: typeof PoliticaDeDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equilibrio': {
      id: '/equilibrio'
      path: '/equilibrio'
      fullPath: '/equilibrio'
      preLoaderRoute: typeof EquilibrioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof EventosRoute
    }
    '/equilibrio/': {
      id: '/equilibrio/'
      path: '/'
      fullPath: '/equilibrio/'
      preLoaderRoute: typeof EquilibrioIndexRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/eventos/$seriesSlug': {
      id: '/eventos/$seriesSlug'
      path: '/$seriesSlug'
      fullPath: '/eventos/$seriesSlug'
      preLoaderRoute: typeof EventosSeriesSlugRouteImport
      parentRoute: typeof EventosRoute
    }
    '/equilibrio/registro-exitoso': {
      id: '/equilibrio/registro-exitoso'
      path: '/registro-exitoso'
      fullPath: '/equilibrio/registro-exitoso'
      preLoaderRoute: typeof EquilibrioRegistroExitosoRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/equilibrio/feedback-exitoso': {
      id: '/equilibrio/feedback-exitoso'
      path: '/feedback-exitoso'
      fullPath: '/equilibrio/feedback-exitoso'
      preLoaderRoute: typeof EquilibrioFeedbackExitosoRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/equilibrio/feedback': {
      id: '/equilibrio/feedback'
      path: '/feedback'
      fullPath: '/equilibrio/feedback'
      preLoaderRoute: typeof EquilibrioFeedbackRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/equilibrio/confirmar-asistencia': {
      id: '/equilibrio/confirmar-asistencia'
      path: '/confirmar-asistencia'
      fullPath: '/equilibrio/confirmar-asistencia'
      preLoaderRoute: typeof EquilibrioConfirmarAsistenciaRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/equilibrio/conexion-exitosa': {
      id: '/equilibrio/conexion-exitosa'
      path: '/conexion-exitosa'
      fullPath: '/equilibrio/conexion-exitosa'
      preLoaderRoute: typeof EquilibrioConexionExitosaRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/equilibrio/conexion': {
      id: '/equilibrio/conexion'
      path: '/conexion'
      fullPath: '/equilibrio/conexion'
      preLoaderRoute: typeof EquilibrioConexionRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/equilibrio/asistencia-confirmada': {
      id: '/equilibrio/asistencia-confirmada'
      path: '/asistencia-confirmada'
      fullPath: '/equilibrio/asistencia-confirmada'
      preLoaderRoute: typeof EquilibrioAsistenciaConfirmadaRouteImport
      parentRoute: typeof EquilibrioRoute
    }
    '/eventos/$seriesSlug/': {
      id: '/eventos/$seriesSlug/'
      path: '/'
      fullPath: '/eventos/$seriesSlug/'
      preLoaderRoute: typeof EventosSeriesSlugIndexRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
    '/eventos/$seriesSlug/registro-exitoso': {
      id: '/eventos/$seriesSlug/registro-exitoso'
      path: '/registro-exitoso'
      fullPath: '/eventos/$seriesSlug/registro-exitoso'
      preLoaderRoute: typeof EventosSeriesSlugRegistroExitosoRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
    '/eventos/$seriesSlug/feedback-exitoso': {
      id: '/eventos/$seriesSlug/feedback-exitoso'
      path: '/feedback-exitoso'
      fullPath: '/eventos/$seriesSlug/feedback-exitoso'
      preLoaderRoute: typeof EventosSeriesSlugFeedbackExitosoRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
    '/eventos/$seriesSlug/feedback': {
      id: '/eventos/$seriesSlug/feedback'
      path: '/feedback'
      fullPath: '/eventos/$seriesSlug/feedback'
      preLoaderRoute: typeof EventosSeriesSlugFeedbackRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
    '/eventos/$seriesSlug/confirmar-asistencia': {
      id: '/eventos/$seriesSlug/confirmar-asistencia'
      path: '/confirmar-asistencia'
      fullPath: '/eventos/$seriesSlug/confirmar-asistencia'
      preLoaderRoute: typeof EventosSeriesSlugConfirmarAsistenciaRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
    '/eventos/$seriesSlug/conexion-exitosa': {
      id: '/eventos/$seriesSlug/conexion-exitosa'
      path: '/conexion-exitosa'
      fullPath: '/eventos/$seriesSlug/conexion-exitosa'
      preLoaderRoute: typeof EventosSeriesSlugConexionExitosaRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
    '/eventos/$seriesSlug/conexion': {
      id: '/eventos/$seriesSlug/conexion'
      path: '/conexion'
      fullPath: '/eventos/$seriesSlug/conexion'
      preLoaderRoute: typeof EventosSeriesSlugConexionRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
    '/eventos/$seriesSlug/asistencia-confirmada': {
      id: '/eventos/$seriesSlug/asistencia-confirmada'
      path: '/asistencia-confirmada'
      fullPath: '/eventos/$seriesSlug/asistencia-confirmada'
      preLoaderRoute: typeof EventosSeriesSlugAsistenciaConfirmadaRouteImport
      parentRoute: typeof EventosSeriesSlugRoute
    }
  }
}

interface EquilibrioRouteChildren {
  EquilibrioAsistenciaConfirmadaRoute: typeof EquilibrioAsistenciaConfirmadaRoute
  EquilibrioConexionRoute: typeof EquilibrioConexionRoute
  EquilibrioConexionExitosaRoute: typeof EquilibrioConexionExitosaRoute
  EquilibrioConfirmarAsistenciaRoute: typeof EquilibrioConfirmarAsistenciaRoute
  EquilibrioFeedbackRoute: typeof EquilibrioFeedbackRoute
  EquilibrioFeedbackExitosoRoute: typeof EquilibrioFeedbackExitosoRoute
  EquilibrioRegistroExitosoRoute: typeof EquilibrioRegistroExitosoRoute
  EquilibrioIndexRoute: typeof EquilibrioIndexRoute
}

const EquilibrioRouteChildren: EquilibrioRouteChildren = {
  EquilibrioAsistenciaConfirmadaRoute: EquilibrioAsistenciaConfirmadaRoute,
  EquilibrioConexionRoute: EquilibrioConexionRoute,
  EquilibrioConexionExitosaRoute: EquilibrioConexionExitosaRoute,
  EquilibrioConfirmarAsistenciaRoute: EquilibrioConfirmarAsistenciaRoute,
  EquilibrioFeedbackRoute: EquilibrioFeedbackRoute,
  EquilibrioFeedbackExitosoRoute: EquilibrioFeedbackExitosoRoute,
  EquilibrioRegistroExitosoRoute: EquilibrioRegistroExitosoRoute,
  EquilibrioIndexRoute: EquilibrioIndexRoute,
}

const EquilibrioRouteWithChildren = EquilibrioRoute._addFileChildren(
  EquilibrioRouteChildren,
)

interface EventosSeriesSlugRouteChildren {
  EventosSeriesSlugAsistenciaConfirmadaRoute: typeof EventosSeriesSlugAsistenciaConfirmadaRoute
  EventosSeriesSlugConexionRoute: typeof EventosSeriesSlugConexionRoute
  EventosSeriesSlugConexionExitosaRoute: typeof EventosSeriesSlugConexionExitosaRoute
  EventosSeriesSlugConfirmarAsistenciaRoute: typeof EventosSeriesSlugConfirmarAsistenciaRoute
  EventosSeriesSlugFeedbackRoute: typeof EventosSeriesSlugFeedbackRoute
  EventosSeriesSlugFeedbackExitosoRoute: typeof EventosSeriesSlugFeedbackExitosoRoute
  EventosSeriesSlugRegistroExitosoRoute: typeof EventosSeriesSlugRegistroExitosoRoute
  EventosSeriesSlugIndexRoute: typeof EventosSeriesSlugIndexRoute
}

const EventosSeriesSlugRouteChildren: EventosSeriesSlugRouteChildren = {
  EventosSeriesSlugAsistenciaConfirmadaRoute:
    EventosSeriesSlugAsistenciaConfirmadaRoute,
  EventosSeriesSlugConexionRoute: EventosSeriesSlugConexionRoute,
  EventosSeriesSlugConexionExitosaRoute: EventosSeriesSlugConexionExitosaRoute,
  EventosSeriesSlugConfirmarAsistenciaRoute:
    EventosSeriesSlugConfirmarAsistenciaRoute,
  EventosSeriesSlugFeedbackRoute: EventosSeriesSlugFeedbackRoute,
  EventosSeriesSlugFeedbackExitosoRoute: EventosSeriesSlugFeedbackExitosoRoute,
  EventosSeriesSlugRegistroExitosoRoute: EventosSeriesSlugRegistroExitosoRoute,
  EventosSeriesSlugIndexRoute: EventosSeriesSlugIndexRoute,
}

const EventosSeriesSlugRouteWithChildren =
  EventosSeriesSlugRoute._addFileChildren(EventosSeriesSlugRouteChildren)

interface EventosRouteChildren {
  EventosSeriesSlugRoute: typeof EventosSeriesSlugRouteWithChildren
  EventosIndexRoute: typeof EventosIndexRoute
}

const EventosRouteChildren: EventosRouteChildren = {
  EventosSeriesSlugRoute: EventosSeriesSlugRouteWithChildren,
  EventosIndexRoute: EventosIndexRoute,
}

const EventosRouteWithChildren =
  EventosRoute._addFileChildren(EventosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EquilibrioRoute: EquilibrioRouteWithChildren,
  EventosRoute: EventosRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliticaDeDatosRoute: PoliticaDeDatosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
